// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrpqnzelszrverzsdkkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycHFuemVsc3pydmVyenNka2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODIwODksImV4cCI6MjA3MTM1ODA4OX0.JzcI5QZA7SzZr1PA3D15-yKfzQNYXzFHe0N7R6ttDWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});